name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python3 -m pip3 install --upgrade pip3
        pip3 install pylint
        pip3 install ply
    - name: Analysing the code with pylint
      run: |
        cd src/
        pylint `ls -R|grep .py$|xargs`
