# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python-version }}

      # Runs a single command using the runners shell
      - name: install required packages
        run: |
          python -m pip install --upgrade pip
          pip3 install ply
        

      # Runs a set of commands using the runners shell
      - name: Running test on lexer
        run: |
          chmod +x test.sh
          chmod +x bin/lexer
          sudo chown -R  root *
          sudo ./test.sh
          if [[ $? -ne 0 ]];
          then
            echo "PROGRAM FAILED ON TEST CASES"
            exit 1
          fi
